grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
from django.conf.urls.defaults import *
from django.conf import settings


urlpatterns = patterns('',
    
    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', 'grappelli.views.related.related_lookup', name="grp_related_lookup"),
    url(r'^lookup/m2m/$', 'grappelli.views.related.m2m_lookup', name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', 'grappelli.views.related.autocomplete_lookup', name="grp_autocomplete_lookup"),
    
)

urls.py
from django.views.generic.simple import direct_to_template
from django.conf.urls.defaults import *
from django.conf import settings

handler500 = 'neighborlink.apps.content.views.server_error'

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^nlink/', include('nlink.foo.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
)

if settings.DEBUG:
  urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True }),
  )

from neighborlink.apps.content.feeds import *
urlpatterns += patterns('',
    (r'^news-and-events/feed/$', LatestNewsEventsFeed()),
    (r'^about/feed/$', LatestAboutPageFeed()),
    (r'^login/$', direct_to_template, {'template': 'login.html'}),
)

urlpatterns += patterns('neighborlink.apps.entity.views',
    (r'^businesses/$', 'business_list'),
    (r'^businesses/(?P<slug>[\w-]+)/$', 'business_detail'),
    (r'^churches/$', 'church_list'),
    (r'^churches/(?P<slug>[\w-]+)/$', 'church_detail'),
    (r'^services/$', 'service_list'),
    (r'^services/(?P<slug>[\w-]+)/$', 'service_detail'),
)

urlpatterns += patterns('neighborlink.apps.content.views',
    (r'^news-and-events/(?P<slug>[\w-]+)/$', 'newsevent_detail'),
    (r'^news-and-events/$', 'newsevent_list'),
    (r'^about/(?P<slug>[\w-]+)/$', 'about_detail'),
    (r'^about/$', 'about_list'),
    (r'^resources/(?P<slug>[\w-]+)/$', 'resource_detail'),
    (r'^resources/$', 'resource_list'),
    (r'^community-association/$', 'community_association_list'),
    (r'^community-association/(?P<slug>[\w-]+)/$', 'community_association_detail'),

    (r'^$', 'home'),
)

apps/content/models.py
from django.db import models
from datetime import datetime

class PageInfo(models.Model):
    insert_date = models.DateField(null=True, auto_now_add=True, editable=False)
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=255)
    teaser = models.CharField(max_length=1024, null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    approved = models.BooleanField(default=False)
    parent = models.ForeignKey('self', null=True, blank=True)
    sort_order = models.IntegerField()

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ('sort_order',)
        permissions = (
            ("can_approve_post", "Can approve post"),
        )

    def clean(self):
        from django.core.exceptions import ValidationError
        model = self.__class__

        if self.slug:
            try:
                model.objects.exclude(pk=self.pk).get(slug__exact=self.slug)
                raise ValidationError('This slug has already been used.')
            except model.DoesNotExist:
                pass


    def save(self, *args, **kwargs):
        mode = self.__class__

        if self.sort_order is None:
            try:
                last = model.objects.order_by('-sort_order')[0]
                self.sort_order = last.sort_order + 1
            except IndexError:
                self.sort_order = 0
        super(PageInfo, self).save(*args, **kwargs)

class Page(PageInfo):
    pass    

class Heroshot(models.Model):
    image = models.ImageField(upload_to='ext/heroshots/content')
    description = models.CharField(max_length=255, blank=True, null=True)
    url = models.CharField(max_length=255,blank=True)
    sort_order = models.PositiveIntegerField(null=True, blank=True)
    page = models.ForeignKey(PageInfo)   
    
    class Meta:
        ordering = ['sort_order',]

class AboutPage(PageInfo):
    pass

    def get_absolute_url(self):
        return '/about/%s/' % self.slug

class ResourcePage(PageInfo):
    pass

    def get_absolute_url(self):
        return '/resources/%s/' % self.slug

    

class CommunityAssocationPage(PageInfo):
    pass
    
    def get_absolute_url(self):
        return '/community-association/%s/' % self.slug        

class NewsEvent(PageInfo):
    start_date = models.DateField(null=True, verbose_name='Date to start display')
    end_date = models.DateField(null=True, verbose_name='Date to end display')
    event_start_date = models.DateTimeField(null=True, blank=True)
    event_end_date = models.DateTimeField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.start_date:
            self.start_date = datetime.now()
        super(NewsEvent, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return '/news-and-events/%s/' % self.slug

    def get_date_string(self):
        #   Saturday, December 11th, 2011 from 2 to 6 pm
        start_date = self.event_start_date
        end_date = self.event_end_date
        if not start_date:
            return ''

        ds = start_date.day
        if ds%10 == 1 and ds != 11:
            ds = "%dst" % ds
        elif ds%10 == 2:
            ds = "%dnd" % ds
        elif ds%10 == 3:
            ds = "%drd" % ds
        else:
            ds = "%dth" % ds
        
        #   TO-DO: Deal with half hours
        if start_date.year == end_date.year and start_date.month == end_date.month and start_date.day == end_date.day:
            #  Same day
            ds = start_date.strftime('%A, %B') + (" %s " % ds) + start_date.strftime('%Y') + " from"
            
            if start_date.strftime('%p') == end_date.strftime('%p'):
                ds = "%s %d to %d %s" % (ds, int(start_date.strftime('%I')), int(end_date.strftime('%I')), start_date.strftime('%p'))
            else:
                ds = "%s %d %s to %d %s" % (ds, int(start_date.strftime('%I')), start_date.strftime('%p'), int(end_date.strftime('%I')), end_date.strftime('%p'))
        else:
            ds = start_date.strftime('%A, %B') + " until " + end_date.strftime('%A, %B')

        return ds
        
    date_string = property(get_date_string)    
    
from django.contrib.syndication.views import Feed    

apps/stelmo/models.py
from neighborlink.apps.stelmo.listeners import *

apps/content/views.py
from django.template import RequestContext, Context, loader
from django.shortcuts import render_to_response, get_object_or_404
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.http import HttpResponseRedirect
from datetime import datetime
from django.conf import settings
from django import http
from django.http import Http404

from neighborlink.apps.content.models import *

def server_error(request, template_name='500.html'):
    """
    500 error handler.

    Templates: `500.html`
    Context:
        MEDIA_URL
            Path of static media (e.g. "media.example.org")
    """
    t = loader.get_template(template_name) # You need to create a 500.html template.

    return http.HttpResponseServerError(t.render(Context({
        'MEDIA_URL': settings.MEDIA_URL
    })))   

def home(request):
    from neighborlink.apps.entity.models import Featured, Business

    contentpage = get_object_or_404(Page, slug__exact='home')
    recent_events = NewsEvent.objects.filter(start_date__lte=datetime.now(), end_date__gte=datetime.now(), approved=True).order_by('-start_date', '-event_start_date')[:2]

    featured_business = Featured.objects.filter(entity__approved=True).order_by('-date_featured')
    if not featured_business:
        #   Pick a random featurable business
        featured_business = Business.objects.filter(featurable=True, approved=True).order_by('?')[0]

    context = RequestContext(request, {
        'contentpage': contentpage,
        'recent_events': recent_events,
        'featured_business': featured_business
    })
    
    return render_to_response('content/home.html', {}, context_instance=context)

def page_list(request, contentpage, items_list, slug, per_page=5):
    paginator = Paginator(items_list, per_page)

    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        items = paginator.page(page)
    except (EmptyPage, InvalidPage):
        items = paginator.page(paginator.num_pages)

    return RequestContext(request, {
        'contentpage': contentpage,
        'page': page,
        'items': items,
        'recent_items': items_list[:10],
        'slug': slug,
    })

def page_detail(request, item, recent_entries, slug):
    return RequestContext(request, {
        'item': item,
        'recent_entries': recent_entries,
        'slug': slug,
    })

def newsevent_list(request):
    slug = 'news-and-events'
    contentpage = get_object_or_404(Page, slug__exact=slug, approved=True)
    events_list = NewsEvent.objects.filter(start_date__lte=datetime.now(), end_date__gte=datetime.now(), approved=True).order_by('sort_order', '-start_date', '-event_start_date')

    context = page_list(request, contentpage, events_list, slug)

    return render_to_response('content/newsevent_list.html', {}, context_instance=context)

def newsevent_detail(request, slug):
    event = get_object_or_404(NewsEvent, slug__exact=slug)
    if (event.start_date and event.start_date > datetime.now().date()) or (event.end_date and event.end_date < datetime.now().date()):
        raise Http404('Page Not Found')

    recent_entries = NewsEvent.objects.filter(start_date__lte=datetime.now(), end_date__gte=datetime.now(), approved=True).exclude(slug__exact=slug).order_by('start_date', 'event_start_date')[:6]

    context = page_detail(request, event, recent_entries, 'news-and-events')

    return render_to_response('content/newsevent_detail.html', {}, context_instance=context)

def about_list(request):
    slug = 'about'
    contentpage = get_object_or_404(Page, slug__exact=slug, approved=True)
    about_list = AboutPage.objects.filter(approved=True).order_by('sort_order')

    context = page_list(request, contentpage, about_list, slug)

    return render_to_response('content/about_list.html', {}, context_instance=context)

def about_detail(request, slug):
    about = get_object_or_404(AboutPage, slug__exact=slug)
    recent_entries = AboutPage.objects.filter(approved=True).exclude(slug__exact=slug).order_by('sort_order')[:6]

    context = page_detail(request, about, recent_entries, 'about')

    return render_to_response('content/about_detail.html', {}, context_instance=context)   

def resource_list(request):
    slug = 'resources'
    contentpage = get_object_or_404(Page, slug__exact=slug, approved=True)
    resource_list = ResourcePage.objects.filter(approved=True).order_by('sort_order')

    context = page_list(request, contentpage, resource_list, slug)

    return render_to_response('content/resource_list.html', {}, context_instance=context)

def resource_detail(request, slug):
    resource = get_object_or_404(ResourcePage, slug__exact=slug)
    recent_entries = ResourcePage.objects.filter(approved=True).exclude(slug__exact=slug).order_by('sort_order')[:6]

    context = page_detail(request, resource, recent_entries, 'resources')

    return render_to_response('content/resource_detail.html', {}, context_instance=context)

def community_association_list(request):
    slug = 'community-association'
    contentpage = get_object_or_404(Page, slug__exact=slug, approved=True)
    community_association_list = CommunityAssocationPage.objects.filter(approved=True).order_by('sort_order')

    context = page_list(request, contentpage, community_association_list, slug)

    return render_to_response('content/community_association_list.html', {}, context_instance=context)

def community_association_detail(request, slug):
    community_association_page = get_object_or_404(CommunityAssocationPage, slug__exact=slug)
    recent_entries = CommunityAssocationPage.objects.filter(approved=True).exclude(slug__exact=slug).order_by('sort_order')[:6]

    context = page_detail(request, community_association_page, recent_entries, 'community-association')

    return render_to_response('content/community_association_detail.html', {}, context_instance=context)
    

templates/st-elmo/content/about_detail.html
{% extends "content/page_detail.html" %}

templates/st-elmo/content/about_list.html
{% extends "content/page_list.html" %}

{% block content %}
	{{ block.super }}
{% endblock content %}

{% block title %}
About St. Elmo
{% endblock title %}

templates/st-elmo/content/community_association_detail.html
{% extends "content/page_detail.html" %}

templates/st-elmo/content/community_association_list.html
{% extends "content/page_list.html" %}

{% block content %}
	{{ block.super }}
{% endblock content %}

{% block title %}
CAHSE
{% endblock title %}

templates/st-elmo/content/home.html
{% extends "base.html" %}

{% block content %}
				<div id="HomeCollage">
					<div id="PhotoSlot1"><img src="{{ MEDIA_URL }}{{ contentpage.heroshot_set.all.0.image }}" height="340" width="279"></div>
					<div id="PhotoSlot2"><img src="{{ MEDIA_URL }}{{ contentpage.heroshot_set.all.1.image }}" height="224" width="394"></div>
					<div id="HistoryBox">
						<div>
							{{ contentpage.content|safe }}
						</div>
						<a href="/about" class="more archb">Learn More &gt;</a>
					</div>
					<div id="PhotoSlot3"><img src="{{ MEDIA_URL }}{{ contentpage.heroshot_set.all.2.image }}" height="113" width="394"></div>
					<div id="NewsletterFrontpage" class="NewsletterForm">
						<div class="teaser archbi">want to stay in the loop?</div>
						<div class="calltoaction archb">join the Neighborhood Email List</div>
						<form action="http://lists.st-elmo.org/mailman/subscribe/neighbors" method="post">
							<input type="text" value="" title="email address" class="email input" name="email">
							<input type="submit" value="Join" class="button submit">
						</form>
					</div>
					<div class="clear"></div>
				</div>
				<div id="FeaturedPanel">
					<div id="FeaturedBusiness" class="standard wide first">
						<div class="Header">Featured Business<a href="/businesses/" class="more">view all &gt;</a></div>
						<div class="Content">
							<div class="Image"><a href="{{ featured_business.get_absolute_url }}"><img src="{% if featured_business.heroshot_slim %}{{ featured_business.heroshot_slim.url }}{% else %}{% if featured_business.heroshot_full %}{{ featured_business.heroshot_full.url }}{% else %}{{ MEDIA_URL }}img/business_no_photo.png{% endif %}{% endif %}" width="324"></a></div>
							<div class="Listing">
								<a href="{{ featured_business.get_absolute_url }}" class="Title">{{ featured_business.name }}</a>
								<div class="subtitle"><em>{{ featured_business.tagline }}</em></div>
								<div class="details">
									<div>{{ featured_business.description|truncatewords_html:40 }}</div>
								</div>
								<a href="{{ featured_business.get_absolute_url }}" class="more">Learn More &gt;</a>
							</div>
						</div>
					</div>
					<div id="RecentNewsPanel" class="standard wide">
						<div class="Header">Recent News &amp; Events<a href="/news-and-events/" class="more">view all &gt;</a></div>
						<div class="Content">
							{% for event in recent_events %}
							<div class="Listing {% ifequal forloop.counter 2 %}last{% endifequal %}">
								{% if event.event_start_date %}<div class="date">{{ event.event_start_date|date:"n.j.y" }}</div>{% endif %}
								<a href="{{ event.get_absolute_url }}" class="Title">{{ event.title }}</a>
								<div class="details">
								{% if event.event_start_date %}
									<strong>When:</strong> {{ event.date_string }}
								{% endif %}
								</div>
								<div class="excerpt">
								{% if event.teaser %}
									{{ event.teaser }}
								{% else %}
									{{ event.content|striptags|truncatewords:15 }}
								{% endif %}
								</div>
								<a href="{{ event.get_absolute_url }}" class="more">Read More &gt;</a>
							</div>
							{% endfor %}
						</div>
					</div>
					<div id="SocialPanel" class="standard thin last">
						<div class="Header">Elsewhere</div>
						<div class="Content">
							{% include "sociallinks.html" %}
						</div>
						{% comment %}<div class="Disclaimer">
							<img src="{{ MEDIA_URL }}img/disclaimer.png" width="186" height="115">
						</div>{% endcomment %}
					</div>
					<div class="clear"></div>
				</div>
{% endblock content %}

templates/st-elmo/content/neighborhood_association_detail.html
{% extends "content/page_detail.html" %}

templates/st-elmo/content/neighborhood_association_list.html
{% extends "content/page_list.html" %}

{% block content %}
	{{ block.super }}
{% endblock content %}

{% block title %}
CAHSE
{% endblock title %}

templates/st-elmo/content/newsevent_detail.html
{% extends "content/page_detail.html" %}

{% block content %}
  {{ block.super }}
{% endblock content %}

{% block sidebar %}
				<div id="SideNavigation">
					<div class="Widget LinkList">
						<div class="Header">Recent Entries<a href="{{ slug }}/feed/" class="more rss"></a></div>
						<div class="Links">
						{% for entry in recent_entries %}
							<a href="{{ entry.get_absolute_url }}"{% ifequal entry.get_absolute_url request.get_full_path %} class="selected"{% endifequal %}>
								{{ entry.title }}<br>
							</a>
						{% endfor %}
						</div>
					</div>
					
					<div class="Widget NewsletterForm">
						<div class="teaser archbi">want to stay in the loop?</div>
						<div class="calltoaction archb">join the Neighborhood Email List</div>
						<form action="/http://lists.st-elmo.org/mailman/subscribe/neighbors" method="post">
							<input type="text" value="" title="email address" class="email input" name="email">
							<input type="submit" value="Join" class="button submit">
						</form>
					</div>
				</div>	
{% endblock sidebar %}

templates/st-elmo/content/newsevent_list.html
{% extends "content/page_list.html" %}

{% block content %}
	{{ block.super }}
{% endblock content %}

{% block title %}
News &amp; Events
{% endblock title %}

templates/st-elmo/content/page_detail.html
{% extends "base.html" %}

{% block content %}
				<div class="span_content span_thin">
					<div id="HeroImage"><img src='{{ MEDIA_URL }}{{ item.heroshot_set.all.0.image|default:"/img/demo/hero_house.png" }}' height="201" width="674"></div>
					<div id="PageContent">
						<h1>{{ item.title|upper }}</h1>
						<div class="Copy">
							{{ item.content|safe }}
						</div>
					</div>
				</div>
	{% block sidebar %}				
				<div id="SideNavigation">
					<div class="Widget LinkList">
						<div class="Header">Recent Entries<a href="{{ slug }}/feed/" class="more rss"></a></div>
						<div class="Links">
						{% for entry in recent_entries %}
							<a href="{{ entry.get_absolute_url }}"{% ifequal entry.get_absolute_url request.get_full_path %} class="selected"{% endifequal %}>
								{{ entry.title }}<br>
								<span>
								{% if entry.teaser %}
									{{ entry.teaser }}
								{% else %}
									{{ entry.content|striptags|truncatewords:15 }}
								{% endif %}
								</span>

							</a>
						{% endfor %}
						</div>
					</div>
					
					<div class="Widget NewsletterForm">
						<div class="teaser archbi">want to stay in the loop?</div>
						<div class="calltoaction archb">join the Neighborhood Email List</div>
						<form action="/http://lists.st-elmo.org/mailman/subscribe/neighbors" method="post">
							<input type="text" value="" title="email address" class="email input" name="email">
							<input type="submit" value="Join" class="button submit">
						</form>
					</div>
				</div>	
	{% endblock sidebar %}					
{% endblock content %}

templates/st-elmo/content/page_list.html
{% extends "base.html" %}

{% block content %}
				<div class="span_content span_thin">
					<div id="HeroImage"><img src='{{ MEDIA_URL }}{{ contentpage.heroshot_set.all.0.image|default:"res/img/demo/hero_working.png" }}' height="201" width="674"></div>
					<div id="PageContent">
						<h1>{% block title %}List Title{% endblock title %}</h1>
  					{% for item in items.object_list %}
						<div class="Listing">
						{% if item.event_start_date %}
							<div class="date">{{ item.event_start_date|date:"n.j.y" }}</div>
						{% endif %}
							<h2><a href="{{ item.get_absolute_url }}">{{ item.title|upper }}</a></h2>
						{% if item.date_string %}
							<div class="details">
								<div><strong>When:</strong> {{ item.date_string }}</div>
							</div>
						{% endif %}
							<div class="Copy">
						{% if item.teaser %}
								<p>{{ item.teaser }}</p>
						{% else %}
								<p>{{ item.content|striptags|truncatewords:15 }}
						{% endif %}
							</div>
							<a href="{{ item.get_absolute_url }}" class="more">Read More &gt;</a>
						</div>
					{% endfor %}
						<div class="pagination">
			  			{% if items.has_previous %}
							<a href="?page={{ items.previous_page_number }}" class="previous">&lt; older entries</a>
						{% endif %}
						{% if items.has_next %}
							<a href="?page={{ items.next_page_number }}" class="next">newer entries &gt;</a>
						{% endif %}
							<div class="clear"></div>
						</div>
					</div>
				</div>
				<div id="SideNavigation">
					<div class="Widget LinkList">
						<div class="Header">Recent Entries<a href="/{{ slug }}/feed/" class="more rss"></a></div>
						<div class="Links">
						{% for item in recent_items %}
							<a href="{{ item.get_absolute_url }}">{{ item.title|upper }}</a>
						{% endfor %}
						</div>
					</div>
					
					<div class="Widget NewsletterForm">
						<div class="teaser archbi">want to stay in the loop?</div>
						<div class="calltoaction archb">join the Neighborhood Email List</div>
						<form action="http://lists.st-elmo.org/mailman/subscribe/neighbors" method="post">
							<input type="text" value="" title="email address" class="email input" name="email">
							<input type="submit" value="Join" class="button submit">
						</form>
					</div>
				</div>						
{% endblock content %}

templates/st-elmo/content/resource_detail.html
{% extends "content/page_detail.html" %}

templates/st-elmo/content/resource_list.html
{% extends "content/page_list.html" %}

{% block content %}
	{{ block.super }}
{% endblock content %}

{% block title %}
Resources
{% endblock title %}